# .github/workflows/release_windows_exe.yml

name: Release Windows Executable

on:
  push:
    tags: # Este workflow se dispara cuando se hace push a un tag (ej: v1.0.0)
      - 'v*' # Coincide con tags que empiezan con 'v' (ej: v1.0, v1.0.1, v2.0.0)
  workflow_dispatch: # Permite ejecutar el workflow manualmente

permissions:
  contents: write # ¡Importante! Necesita permisos de escritura para crear el release y los tags.

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Windows Executable
      run: |
        pyinstaller --noconfirm --onefile --windowed --name FileFinder main.py

    - name: Create Release
      uses: softprops/action-gh-release@v1 # Acción para crear un GitHub Release
      if: startsWith(github.ref, 'refs/tags/') # Asegura que solo se ejecute si es un push de tag
      with:
        files: |
          dist/FileFinder.exe # Archivo .exe a adjuntar al release
          config.json         # config.json externo a adjuntar al release
        name: Release ${{ github.ref_name }} # Título del release (ej: Release v1.0.0)
        tag_name: ${{ github.ref }} # El nombre del tag es el nombre del release
        body: | # Descripción del release (puedes personalizar esto)
          🎉 New Release: ${{ github.ref_name }} 🎉